`resetall
`timescale 1ns / 1ps
`default_nettype none

/*
 * ============================================================================
 * AXI4 -> AXI4-Lite UART ADAPTER
 * ============================================================================
 *
 * Project:
 *   VeeR EL2 RISC-V based hardware packet buffering and data integrity SoC
 *
 * Purpose:
 *   Bridges the AXI4 M02 interface of axi_interconnect_wrap_1x8 to the
 *   AXI4-Lite-style interface of axi_uart_top.
 *
 * System connection:
 *
 *   axi_master_project
 *          |
 *        AXI4
 *          |
 *   axi_interconnect_wrap_1x8
 *          |
 *         M02
 *          |
 *          v
 *   axi4_to_axi4lite_uart_adapter
 *          |
 *      AXI4-Lite-style
 *          |
 *          v
 *      axi_uart_top
 *
 * IMPORTANT:
 *   The supplied UART top is documented as AXI4-Lite, but its interface
 *   contains an ID field. Its internal write logic also requires AWVALID
 *   and WVALID to be asserted together, and its response valid signals
 *   remain gated by those request-valid signals. Therefore this adapter:
 *
 *   1. Buffers AXI4 AW and W independently.
 *   2. Presents AWVALID and WVALID together to the UART.
 *   3. Holds both UART request VALID signals until the UART B response is
 *      accepted.
 *   4. Holds UART ARVALID until the UART R response is accepted.
 *   5. Converts 32-bit AXI addresses to the UART's 5-bit local address.
 *   6. Converts the project 8-bit AXI ID to the UART's 12-bit ID by
 *      zero-extension.
 *   7. Converts the UART's 12-bit response ID back to the project's
 *      8-bit ID by truncation.
 *   8. Uses one clock for the adapter, AXI interconnect, and both UART
 *      clock inputs. This is the recommended first integration arrangement.
 *
 * UART local register addressing:
 *
 *   UART top uses axi_araddr_i[4:2] / axi_awaddr_i[4:2].
 *
 *   Therefore:
 *       local 0x00 -> RBR / THR
 *       local 0x04 -> IER
 *       local 0x08 -> BAUD DIVISOR (when DLAB = 1)
 *       local 0x0C -> LCR
 *       local 0x14 -> LSR
 *
 * Project UART base:
 *       0x0002_0000
 *
 * Thus examples are:
 *       0x0002_0000 -> UART RBR/THR
 *       0x0002_0004 -> UART IER
 *       0x0002_0008 -> UART BAUD DIVISOR
 *       0x0002_000C -> UART LCR
 *       0x0002_0014 -> UART LSR
 *
 * This module supports the single-beat AXI4 transactions generated by the
 * supplied axi_master_project. AXI bursts are intentionally not propagated
 * to the UART because the UART is a register peripheral.
 *
 * ============================================================================
 */

module axi4_to_axi4lite_uart_adapter #
(
    parameter DATA_WIDTH       = 32,
    parameter ADDR_WIDTH       = 32,
    parameter STRB_WIDTH       = (DATA_WIDTH/8),
    parameter S_ID_WIDTH       = 8,     // project/interconnect ID width
    parameter UART_ID_WIDTH    = 12,    // UART IP ID width
    parameter UART_ADDR_WIDTH  = 5
)
(
    input  wire                     clk,
    input  wire                     rst,

    /*
     * ========================================================================
     * AXI4 SLAVE SIDE
     * Connect to M02 of axi_interconnect_wrap_1x8.
     * ========================================================================
     */

    input  wire [S_ID_WIDTH-1:0]    s_axi_awid,
    input  wire [ADDR_WIDTH-1:0]    s_axi_awaddr,
    input  wire [7:0]               s_axi_awlen,
    input  wire [2:0]               s_axi_awsize,
    input  wire [1:0]               s_axi_awburst,
    input  wire                     s_axi_awlock,
    input  wire [3:0]               s_axi_awcache,
    input  wire [2:0]               s_axi_awprot,
    input  wire [3:0]               s_axi_awqos,
    input  wire [3:0]               s_axi_awregion,
    input  wire                     s_axi_awvalid,
    output wire                     s_axi_awready,

    input  wire [DATA_WIDTH-1:0]    s_axi_wdata,
    input  wire [STRB_WIDTH-1:0]    s_axi_wstrb,
    input  wire                     s_axi_wlast,
    input  wire                     s_axi_wvalid,
    output wire                     s_axi_wready,

    output wire [S_ID_WIDTH-1:0]    s_axi_bid,
    output wire [1:0]               s_axi_bresp,
    output wire                     s_axi_bvalid,
    input  wire                     s_axi_bready,

    input  wire [S_ID_WIDTH-1:0]    s_axi_arid,
    input  wire [ADDR_WIDTH-1:0]    s_axi_araddr,
    input  wire [7:0]               s_axi_arlen,
    input  wire [2:0]               s_axi_arsize,
    input  wire [1:0]               s_axi_arburst,
    input  wire                     s_axi_arlock,
    input  wire [3:0]               s_axi_arcache,
    input  wire [2:0]               s_axi_arprot,
    input  wire [3:0]               s_axi_arqos,
    input  wire [3:0]               s_axi_arregion,
    input  wire                     s_axi_arvalid,
    output wire                     s_axi_arready,

    output wire [S_ID_WIDTH-1:0]    s_axi_rid,
    output wire [DATA_WIDTH-1:0]    s_axi_rdata,
    output wire [1:0]               s_axi_rresp,
    output wire                     s_axi_rlast,
    output wire                     s_axi_rvalid,
    input  wire                     s_axi_rready,

    /*
     * ========================================================================
     * UART AXI4-LITE-STYLE SIDE
     * Connect directly to axi_uart_top.
     * ========================================================================
     */

    output wire                     axi_uart_arvalid_i,
    input  wire                     axi_uart_arready_o,
    output wire [UART_ID_WIDTH-1:0] axi_uart_arid_i,
    output wire [UART_ADDR_WIDTH-1:0] axi_uart_araddr_i,

    input  wire [UART_ID_WIDTH-1:0] axi_uart_rid_o,
    input  wire [DATA_WIDTH-1:0]    axi_uart_rdata_o,
    input  wire [1:0]               axi_uart_rresp_o,
    input  wire                     axi_uart_rvalid_o,
    output wire                     axi_uart_rready_i,

    output wire                     axi_uart_awvalid_i,
    input  wire                     axi_uart_awready_o,
    output wire [UART_ID_WIDTH-1:0] axi_uart_awid_i,
    output wire [UART_ADDR_WIDTH-1:0] axi_uart_awaddr_i,

    output wire                     axi_uart_wvalid_i,
    input  wire                     axi_uart_wready_o,
    output wire [DATA_WIDTH-1:0]    axi_uart_wdata_i,
    output wire [STRB_WIDTH-1:0]    axi_uart_wstrb_i,

    input  wire [UART_ID_WIDTH-1:0] axi_uart_bid_o,
    input  wire [1:0]               axi_uart_bresp_o,
    input  wire                     axi_uart_bvalid_o,
    output wire                     axi_uart_bready_i
);

    /*
     * ------------------------------------------------------------------------
     * Command buffering
     * ------------------------------------------------------------------------
     *
     * AXI4 permits AW and W to arrive independently.
     * The UART implementation does NOT: it requires both VALID signals
     * simultaneously. Therefore we buffer them independently.
     */
    reg                         aw_buf_valid;
    reg [S_ID_WIDTH-1:0]        aw_buf_id;
    reg [ADDR_WIDTH-1:0]        aw_buf_addr;

    reg                         w_buf_valid;
    reg [DATA_WIDTH-1:0]        w_buf_data;
    reg [STRB_WIDTH-1:0]        w_buf_strb;

    reg                         write_active;
    reg                         read_active;

    reg [S_ID_WIDTH-1:0]        write_id_reg;
    reg [S_ID_WIDTH-1:0]        read_id_reg;

    reg [UART_ID_WIDTH-1:0]     uart_write_id_reg;
    reg [UART_ID_WIDTH-1:0]     uart_read_id_reg;

    reg [UART_ADDR_WIDTH-1:0]   uart_write_addr_reg;
    reg [UART_ADDR_WIDTH-1:0]   uart_read_addr_reg;

    /*
     * UART request valid registers.
     *
     * These stay asserted until the UART response is accepted.
     */
    reg                         uart_awvalid_reg;
    reg                         uart_wvalid_reg;
    reg                         uart_arvalid_reg;

    /*
     * Read response buffering.
     */
    reg [DATA_WIDTH-1:0]        read_data_reg;
    reg [1:0]                   read_resp_reg;
    reg                         read_resp_valid_reg;

    /*
     * Write response buffering.
     */
    reg [1:0]                   write_resp_reg;
    reg                         write_resp_valid_reg;

    /*
     * ------------------------------------------------------------------------
     * AXI4 upstream READY
     * ------------------------------------------------------------------------
     *
     * We accept one write transaction at a time.
     *
     * AW and W are allowed to arrive in either order.
     */
    assign s_axi_awready =
        !rst &&
        !aw_buf_valid &&
        !write_active &&
        !read_active &&
        !write_resp_valid_reg;

    assign s_axi_wready =
        !rst &&
        !w_buf_valid &&
        !write_active &&
        !read_active &&
        !write_resp_valid_reg;

    /*
     * A read is accepted only when there is no write activity and no pending
     * read response.
     */
    assign s_axi_arready =
        !rst &&
        !read_active &&
        !write_active &&
        !read_resp_valid_reg &&
        !aw_buf_valid &&
        !w_buf_valid &&
        !write_resp_valid_reg;

    /*
     * ------------------------------------------------------------------------
     * AXI4 upstream WRITE RESPONSE
     * ------------------------------------------------------------------------
     */
    assign s_axi_bid   = write_id_reg;
    assign s_axi_bresp = write_resp_reg;
    assign s_axi_bvalid = write_resp_valid_reg;

    /*
     * ------------------------------------------------------------------------
     * AXI4 upstream READ RESPONSE
     * ------------------------------------------------------------------------
     */
    assign s_axi_rid    = read_id_reg;
    assign s_axi_rdata  = read_data_reg;
    assign s_axi_rresp  = read_resp_reg;
    assign s_axi_rlast  = 1'b1;
    assign s_axi_rvalid = read_resp_valid_reg;

    /*
     * ------------------------------------------------------------------------
     * UART SIDE
     * ------------------------------------------------------------------------
     *
     * Address is reduced to the UART's 5-bit local address.
     * Only the low five address bits matter inside axi_uart_top.
     */
    assign axi_uart_awvalid_i = uart_awvalid_reg;
    assign axi_uart_awid_i    = {{(UART_ID_WIDTH-S_ID_WIDTH){1'b0}}, write_id_reg};
    assign axi_uart_awaddr_i  = uart_write_addr_reg;

    assign axi_uart_wvalid_i = uart_wvalid_reg;
    assign axi_uart_wdata_i  = w_buf_data;
    assign axi_uart_wstrb_i  = w_buf_strb;

    assign axi_uart_bready_i = uart_awvalid_reg && uart_wvalid_reg;

    assign axi_uart_arvalid_i = uart_arvalid_reg;
    assign axi_uart_arid_i    = {{(UART_ID_WIDTH-S_ID_WIDTH){1'b0}}, read_id_reg};
    assign axi_uart_araddr_i  = uart_read_addr_reg;

    assign axi_uart_rready_i = uart_arvalid_reg && !read_resp_valid_reg;

    /*
     * ------------------------------------------------------------------------
     * Main bridge state/control
     * ------------------------------------------------------------------------
     */
    always @(posedge clk) begin
        if (rst) begin

            aw_buf_valid        <= 1'b0;
            aw_buf_id           <= {S_ID_WIDTH{1'b0}};
            aw_buf_addr         <= {ADDR_WIDTH{1'b0}};

            w_buf_valid         <= 1'b0;
            w_buf_data          <= {DATA_WIDTH{1'b0}};
            w_buf_strb          <= {STRB_WIDTH{1'b0}};

            write_active        <= 1'b0;
            read_active         <= 1'b0;

            write_id_reg        <= {S_ID_WIDTH{1'b0}};
            read_id_reg         <= {S_ID_WIDTH{1'b0}};

            uart_write_id_reg   <= {UART_ID_WIDTH{1'b0}};
            uart_read_id_reg    <= {UART_ID_WIDTH{1'b0}};

            uart_write_addr_reg <= {UART_ADDR_WIDTH{1'b0}};
            uart_read_addr_reg  <= {UART_ADDR_WIDTH{1'b0}};

            uart_awvalid_reg    <= 1'b0;
            uart_wvalid_reg     <= 1'b0;
            uart_arvalid_reg    <= 1'b0;

            read_data_reg       <= {DATA_WIDTH{1'b0}};
            read_resp_reg       <= 2'b00;
            read_resp_valid_reg <= 1'b0;

            write_resp_reg      <= 2'b00;
            write_resp_valid_reg<= 1'b0;
        end
        else begin

            /*
             * ================================================================
             * Capture AXI4 AW channel
             * ================================================================
             */
            if (s_axi_awvalid && s_axi_awready) begin
                aw_buf_valid <= 1'b1;
                aw_buf_id    <= s_axi_awid;
                aw_buf_addr  <= s_axi_awaddr;
            end

            /*
             * ================================================================
             * Capture AXI4 W channel
             * ================================================================
             */
            if (s_axi_wvalid && s_axi_wready) begin
                w_buf_valid <= 1'b1;
                w_buf_data  <= s_axi_wdata;
                w_buf_strb  <= s_axi_wstrb;
            end

            /*
             * ================================================================
             * Start UART WRITE once both AXI4 pieces are buffered.
             *
             * The UART requires AWVALID and WVALID simultaneously.
             * ================================================================
             */
            if (!write_active &&
                !read_active &&
                aw_buf_valid &&
                w_buf_valid &&
                !uart_awvalid_reg &&
                !uart_wvalid_reg) begin

                write_active        <= 1'b1;

                write_id_reg        <= aw_buf_id;
                uart_write_id_reg   <= {{(UART_ID_WIDTH-S_ID_WIDTH){1'b0}},
                                         aw_buf_id};

                uart_write_addr_reg <= aw_buf_addr[UART_ADDR_WIDTH-1:0];

                uart_awvalid_reg    <= 1'b1;
                uart_wvalid_reg     <= 1'b1;
            end

            /*
             * ================================================================
             * UART WRITE RESPONSE
             *
             * Keep both UART VALID signals asserted until BVALID/BREADY.
             * This is required because the UART internally gates BVALID
             * with AWVALID & WVALID.
             * ================================================================
             */
            if (write_active &&
                uart_bvalid_o &&
                axi_uart_bready_i) begin

                write_resp_reg       <= axi_uart_bresp_o;
                write_resp_valid_reg <= 1'b1;

                uart_awvalid_reg     <= 1'b0;
                uart_wvalid_reg      <= 1'b0;

                write_active         <= 1'b0;

                aw_buf_valid         <= 1'b0;
                w_buf_valid          <= 1'b0;
            end

            /*
             * ================================================================
             * Upstream WRITE RESPONSE consumption
             * ================================================================
             */
            if (write_resp_valid_reg && s_axi_bready) begin
                write_resp_valid_reg <= 1'b0;
            end

            /*
             * ================================================================
             * READ REQUEST
             * ================================================================
             */
            if (s_axi_arvalid && s_axi_arready) begin

                read_active        <= 1'b1;
                read_id_reg        <= s_axi_arid;

                uart_read_id_reg   <=
                    {{(UART_ID_WIDTH-S_ID_WIDTH){1'b0}}, s_axi_arid};

                uart_read_addr_reg <=
                    s_axi_araddr[UART_ADDR_WIDTH-1:0];

                uart_arvalid_reg   <= 1'b1;
            end

            /*
             * ================================================================
             * UART READ RESPONSE
             *
             * Keep ARVALID high until RVALID/RREADY because the supplied
             * UART top gates RVALID using its ARVALID input.
             * ================================================================
             */
            if (read_active &&
                axi_uart_rvalid_o &&
                axi_uart_rready_i) begin

                read_data_reg       <= axi_uart_rdata_o;
                read_resp_reg       <= axi_uart_rresp_o;
                read_resp_valid_reg <= 1'b1;

                uart_arvalid_reg    <= 1'b0;
                read_active         <= 1'b0;
            end

            /*
             * ================================================================
             * Upstream READ RESPONSE consumption
             * ================================================================
             */
            if (read_resp_valid_reg && s_axi_rready) begin
                read_resp_valid_reg <= 1'b0;
            end
        end
    end

endmodule

`default_nettype wire
`resetall
