// =============================================================================
// veer_lsu_axi64_to_axi32_wrapper.v
//
// Purpose : Adapt the VeeR EL2 LSU 64-bit AXI4 master interface to the
//           existing 32-bit AXI4 interconnect (axi_interconnect_wrap_3x8).
//
// Architecture:
//
//   el2_veer_wrapper (LSU AXI master)
//         |
//         | lsu_axi_* (64-bit data, LSU_BUS_TAG-bit ID)
//         v
//   veer_lsu_axi64_to_axi32_wrapper    <-- THIS MODULE
//         |
//         | m_axi_* (32-bit data, M_ID_WIDTH-bit ID)
//         v
//   axi_interconnect_wrap_3x8  (s01_axi_* port)
//
// -----------------------------------------------------------------
// Key facts derived from el2_lsu_bus_buffer.sv source analysis
// -----------------------------------------------------------------
//
// 1. VeeR LSU is ALWAYS single-beat: AWLEN=0, WLAST=1, ARLEN=0, RLAST=1.
//
// 2. DATA LANE ENCODING (obuf_data0_in / obuf_byteen0_in logic):
//      addr[2] == 0  ->  valid data in WDATA[31:0],  WSTRB[3:0]
//      addr[2] == 1  ->  valid data in WDATA[63:32], WSTRB[7:4]
//
// 3. AXI ADDRESS SENT BY VeeR:
//      side-effect == 0 (cacheable):  AWADDR = {addr[31:3], 3'b0}  (8-byte aligned)
//      side-effect == 1 (MMIO):       AWADDR = addr[31:0]          (actual)
//    The correct 32-bit lane is always selected via AWADDR[2].
//    This wrapper preserves AWADDR intact.
//
// 4. SIZE ENCODING (lsu_axi_awsize / lsu_axi_arsize assignments):
//      side-effect == 0:  AWSIZE/ARSIZE = 3'b011 (8-byte)
//      side-effect == 1:  AWSIZE/ARSIZE = {1'b0, obuf_sz[1:0]} (0=byte,1=half,2=word)
//    This wrapper converts AWSIZE/ARSIZE == 3'b011 to 3'b010 (4-byte word)
//    because the downstream bus is 32 bits wide.
//    Side-effect sizes (0..2) are forwarded as-is.
//
// 5. ID MAPPING:
//      VeeR  LSU_BUS_TAG = 4 bits (default from veer.config)
//      Downstream M_ID_WIDTH = 8 bits (axi_interconnect_wrap_3x8)
//      Forward:  m_awid = { {(M_ID_WIDTH-LSU_BUS_TAG){1'b0}}, s_awid }
//      Return:   s_bid  = m_bid[LSU_BUS_TAG-1:0]
//
// 6. READ DATA RECONSTRUCTION (buf_data_in logic in el2_lsu_bus_buffer.sv):
//      buf_data_in[i] = buf_addr[i][2] ? bus_rsp_rdata[63:32]
//                                      : bus_rsp_rdata[31:0];
//    Therefore wrapper must reconstruct:
//      rd_addr[2]==0: s_rdata[63:0] = {32'b0, m_rdata[31:0]}  (lower half)
//      rd_addr[2]==1: s_rdata[63:0] = {m_rdata[31:0], 32'b0}  (upper half)
//
// 7. USER signals on interconnect (AWUSER,WUSER,BUSER,ARUSER,RUSER) are
//    1-bit wide; tied to 0.
//
// 8. Write and read channels operate completely independently (AXI compliant).
//    Only one write and one read may be outstanding at a time (matches VeeR
//    LSU behaviour; VeeR uses AWREADY/ARREADY backpressure to stall if needed).
//
// Limitations:
//   - Only single-beat AXI4 transactions (matches VeeR LSU).
//   - Burst transactions are NOT supported (not generated by VeeR LSU).
//   - One outstanding write, one outstanding read.
// =============================================================================

`resetall
`timescale 1ns / 1ps
`default_nettype none

module veer_lsu_axi64_to_axi32_wrapper #(
    // Width of VeeR LSU_BUS_TAG (default 4, matches veer.config default)
    parameter LSU_BUS_TAG   = 4,
    // Width of downstream AXI ID bus (axi_interconnect_wrap_3x8 default = 8)
    parameter M_ID_WIDTH    = 8
)(
    input  wire                     clk,
    input  wire                     rst_n,  // Active-low synchronous or asynchronous reset

    // =========================================================================
    // SLAVE side -- connects to VeeR EL2 lsu_axi_* master outputs
    // =========================================================================

    // --- Write Address channel (from VeeR) ---
    input  wire                     s_axi_awvalid,
    output wire                     s_axi_awready,
    input  wire [LSU_BUS_TAG-1:0]   s_axi_awid,
    input  wire [31:0]              s_axi_awaddr,
    input  wire [7:0]               s_axi_awlen,    // Always 8'h00 from VeeR
    input  wire [2:0]               s_axi_awsize,
    input  wire [1:0]               s_axi_awburst,
    input  wire                     s_axi_awlock,
    input  wire [3:0]               s_axi_awcache,
    input  wire [2:0]               s_axi_awprot,
    input  wire [3:0]               s_axi_awqos,
    input  wire [3:0]               s_axi_awregion, // Not forwarded to interconnect

    // --- Write Data channel (from VeeR) ---
    input  wire                     s_axi_wvalid,
    output wire                     s_axi_wready,
    input  wire [63:0]              s_axi_wdata,    // 64-bit from VeeR
    input  wire [7:0]               s_axi_wstrb,    // 8-bit from VeeR
    input  wire                     s_axi_wlast,    // Always 1 from VeeR

    // --- Write Response channel (to VeeR) ---
    output wire                     s_axi_bvalid,
    input  wire                     s_axi_bready,
    output wire [LSU_BUS_TAG-1:0]   s_axi_bid,
    output wire [1:0]               s_axi_bresp,

    // --- Read Address channel (from VeeR) ---
    input  wire                     s_axi_arvalid,
    output wire                     s_axi_arready,
    input  wire [LSU_BUS_TAG-1:0]   s_axi_arid,
    input  wire [31:0]              s_axi_araddr,
    input  wire [7:0]               s_axi_arlen,    // Always 8'h00 from VeeR
    input  wire [2:0]               s_axi_arsize,
    input  wire [1:0]               s_axi_arburst,
    input  wire                     s_axi_arlock,
    input  wire [3:0]               s_axi_arcache,
    input  wire [2:0]               s_axi_arprot,
    input  wire [3:0]               s_axi_arqos,
    input  wire [3:0]               s_axi_arregion, // Not forwarded

    // --- Read Data channel (to VeeR) ---
    output wire                     s_axi_rvalid,
    input  wire                     s_axi_rready,
    output wire [LSU_BUS_TAG-1:0]   s_axi_rid,
    output wire [63:0]              s_axi_rdata,    // 64-bit back to VeeR
    output wire [1:0]               s_axi_rresp,
    output wire                     s_axi_rlast,    // Always 1

    // =========================================================================
    // MASTER side -- connects to axi_interconnect_wrap_3x8 s01_axi_* inputs
    // =========================================================================

    // --- Write Address channel (to interconnect) ---
    output wire                     m_axi_awvalid,
    input  wire                     m_axi_awready,
    output wire [M_ID_WIDTH-1:0]    m_axi_awid,
    output wire [31:0]              m_axi_awaddr,
    output wire [7:0]               m_axi_awlen,
    output wire [2:0]               m_axi_awsize,
    output wire [1:0]               m_axi_awburst,
    output wire                     m_axi_awlock,
    output wire [3:0]               m_axi_awcache,
    output wire [2:0]               m_axi_awprot,
    output wire [3:0]               m_axi_awqos,
    output wire                     m_axi_awuser,   // Tied 0

    // --- Write Data channel (to interconnect) ---
    output wire                     m_axi_wvalid,
    input  wire                     m_axi_wready,
    output wire [31:0]              m_axi_wdata,    // 32-bit to interconnect
    output wire [3:0]               m_axi_wstrb,    // 4-bit to interconnect
    output wire                     m_axi_wlast,
    output wire                     m_axi_wuser,    // Tied 0

    // --- Write Response channel (from interconnect) ---
    input  wire                     m_axi_bvalid,
    output wire                     m_axi_bready,
    input  wire [M_ID_WIDTH-1:0]    m_axi_bid,
    input  wire [1:0]               m_axi_bresp,
    input  wire                     m_axi_buser,    // Ignored

    // --- Read Address channel (to interconnect) ---
    output wire                     m_axi_arvalid,
    input  wire                     m_axi_arready,
    output wire [M_ID_WIDTH-1:0]    m_axi_arid,
    output wire [31:0]              m_axi_araddr,
    output wire [7:0]               m_axi_arlen,
    output wire [2:0]               m_axi_arsize,
    output wire [1:0]               m_axi_arburst,
    output wire                     m_axi_arlock,
    output wire [3:0]               m_axi_arcache,
    output wire [2:0]               m_axi_arprot,
    output wire [3:0]               m_axi_arqos,
    output wire                     m_axi_aruser,   // Tied 0

    // --- Read Data channel (from interconnect) ---
    input  wire                     m_axi_rvalid,
    output wire                     m_axi_rready,
    input  wire [M_ID_WIDTH-1:0]    m_axi_rid,
    input  wire [31:0]              m_axi_rdata,    // 32-bit from interconnect
    input  wire [1:0]               m_axi_rresp,
    input  wire                     m_axi_rlast,
    input  wire                     m_axi_ruser     // Ignored
);

    // =========================================================================
    // WRITE PATH STATE MACHINE
    // =========================================================================
    //
    //  WS_IDLE  : quiescent; accepting AW and/or W from VeeR
    //  WS_WAIT  : waiting for whichever channel (AW or W) arrived second
    //  WS_CMD   : both AW and W latched; forwarding to downstream
    //  WS_BRESP : both sent; waiting for B response from downstream
    //
    //  The AW and W channels are accepted independently.  VeeR may issue them
    //  in the same cycle or in separate cycles (both orders are legal AXI).

    localparam [1:0] WS_IDLE  = 2'd0;
    localparam [1:0] WS_WAIT  = 2'd1;  // First channel in; waiting for second
    localparam [1:0] WS_CMD   = 2'd2;  // Both captured; driving downstream
    localparam [1:0] WS_BRESP = 2'd3;  // Downstream txn done; relaying B

    reg [1:0] wr_state, wr_state_next;

    // AW latch
    reg [LSU_BUS_TAG-1:0] wr_id;
    reg [31:0]            wr_addr;
    reg [2:0]             wr_size;
    reg [1:0]             wr_burst;
    reg                   wr_lock;
    reg [3:0]             wr_cache;
    reg [2:0]             wr_prot;
    reg [3:0]             wr_qos;
    reg                   wr_aw_valid;  // AW has been captured this txn

    // W latch
    reg [63:0]            wr_data64;
    reg [7:0]             wr_strb8;
    reg                   wr_w_valid;   // W has been captured this txn

    // Downstream AW/W sent flags
    reg                   wr_aw_sent;
    reg                   wr_w_sent;

    // Registered downstream AW and W valid drives
    reg                   m_awvalid_r;
    reg                   m_wvalid_r;

    // -------------------------------------------------------------------------
    // Slave-side channel ready signals
    // -------------------------------------------------------------------------
    // AW is accepted:
    //   - In WS_IDLE when AW has not yet been taken (wr_aw_valid=0)
    //   - In WS_WAIT when we are waiting for AW (wr_aw_valid=0, wr_w_valid=1)
    // W is accepted:
    //   - In WS_IDLE when W  has not yet been taken (wr_w_valid=0)
    //   - In WS_WAIT when we are waiting for W  (wr_w_valid=0, wr_aw_valid=1)

    assign s_axi_awready = ((wr_state == WS_IDLE) || (wr_state == WS_WAIT)) &&
                           !wr_aw_valid;
    assign s_axi_wready  = ((wr_state == WS_IDLE) || (wr_state == WS_WAIT)) &&
                           !wr_w_valid;

    // Handshake pulses
    wire aw_take = s_axi_awvalid && s_axi_awready;
    wire w_take  = s_axi_wvalid  && s_axi_wready;

    // -------------------------------------------------------------------------
    // AW latch
    // -------------------------------------------------------------------------
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            wr_aw_valid <= 1'b0;
            wr_id       <= {LSU_BUS_TAG{1'b0}};
            wr_addr     <= 32'b0;
            wr_size     <= 3'b0;
            wr_burst    <= 2'b0;
            wr_lock     <= 1'b0;
            wr_cache    <= 4'b0;
            wr_prot     <= 3'b0;
            wr_qos      <= 4'b0;
        end else begin
            if (wr_state_next == WS_IDLE && wr_state != WS_IDLE) begin
                // Transaction retiring -- clear accepted flag for next txn
                wr_aw_valid <= 1'b0;
            end
            if (aw_take) begin
                wr_aw_valid <= 1'b1;
                wr_id       <= s_axi_awid;
                wr_addr     <= s_axi_awaddr;
                wr_size     <= s_axi_awsize;
                wr_burst    <= s_axi_awburst;
                wr_lock     <= s_axi_awlock;
                wr_cache    <= s_axi_awcache;
                wr_prot     <= s_axi_awprot;
                wr_qos      <= s_axi_awqos;
            end
        end
    end

    // -------------------------------------------------------------------------
    // W latch
    // -------------------------------------------------------------------------
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            wr_w_valid <= 1'b0;
            wr_data64  <= 64'b0;
            wr_strb8   <= 8'b0;
        end else begin
            if (wr_state_next == WS_IDLE && wr_state != WS_IDLE)
                wr_w_valid <= 1'b0;
            if (w_take) begin
                wr_w_valid <= 1'b1;
                wr_data64  <= s_axi_wdata;
                wr_strb8   <= s_axi_wstrb;
            end
        end
    end

    // -------------------------------------------------------------------------
    // Write path state machine (combinational)
    // -------------------------------------------------------------------------
    always @(*) begin
        wr_state_next = wr_state;
        case (wr_state)
            WS_IDLE: begin
                // Both arrive together
                if (aw_take && w_take)
                    wr_state_next = WS_CMD;
                // Only one arrives
                else if (aw_take || w_take)
                    wr_state_next = WS_WAIT;
            end

            WS_WAIT: begin
                // Second channel arrives
                if (aw_take || w_take)
                    wr_state_next = WS_CMD;
            end

            WS_CMD: begin
                // Both downstream channels acknowledged -> wait for B
                if (wr_aw_sent && wr_w_sent)
                    wr_state_next = WS_BRESP;
                // Handle same-cycle completion
                else if ((m_awvalid_r && m_axi_awready) || wr_aw_sent) begin
                    if ((m_wvalid_r  && m_axi_wready)  || wr_w_sent)
                        wr_state_next = WS_BRESP;
                end
            end

            WS_BRESP: begin
                // B arrives from downstream and VeeR accepts it
                if (m_axi_bvalid && s_axi_bready)
                    wr_state_next = WS_IDLE;
            end

            default: wr_state_next = WS_IDLE;
        endcase
    end

    // Write state register
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            wr_state <= WS_IDLE;
        else
            wr_state <= wr_state_next;
    end

    // -------------------------------------------------------------------------
    // Downstream AW/W valid registers
    // -------------------------------------------------------------------------
    // Raised in WS_CMD when the respective channel has not yet been sent.
    // Lowered when the downstream acknowledges.

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            m_awvalid_r <= 1'b0;
            m_wvalid_r  <= 1'b0;
        end else begin
            // Clear on reset to IDLE
            if (wr_state_next == WS_IDLE && wr_state != WS_IDLE) begin
                m_awvalid_r <= 1'b0;
                m_wvalid_r  <= 1'b0;
            end else begin
                // Raise when we enter WS_CMD
                if (wr_state_next == WS_CMD && wr_state != WS_CMD) begin
                    m_awvalid_r <= 1'b1;
                    m_wvalid_r  <= 1'b1;
                end
                // Lower on downstream handshake
                if (m_awvalid_r && m_axi_awready)
                    m_awvalid_r <= 1'b0;
                if (m_wvalid_r  && m_axi_wready)
                    m_wvalid_r  <= 1'b0;
            end
        end
    end

    assign m_axi_awvalid = m_awvalid_r;
    assign m_axi_wvalid  = m_wvalid_r;

    // -------------------------------------------------------------------------
    // Sent flags -- used in WS_CMD -> WS_BRESP transition
    // -------------------------------------------------------------------------
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            wr_aw_sent <= 1'b0;
            wr_w_sent  <= 1'b0;
        end else begin
            if (wr_state_next == WS_IDLE && wr_state != WS_IDLE) begin
                wr_aw_sent <= 1'b0;
                wr_w_sent  <= 1'b0;
            end else begin
                if (m_awvalid_r && m_axi_awready) wr_aw_sent <= 1'b1;
                if (m_wvalid_r  && m_axi_wready)  wr_w_sent  <= 1'b1;
            end
        end
    end

    // -------------------------------------------------------------------------
    // Data lane selection
    // -------------------------------------------------------------------------
    // addr[2] selects which 32-bit half of the 64-bit VeeR bus contains the data.
    // Always use the latched wr_addr because by the time we drive downstream
    // (WS_CMD) both AW and W have already been captured.

    wire        wr_lane_sel = wr_addr[2];
    wire [31:0] wdata32     = wr_lane_sel ? wr_data64[63:32] : wr_data64[31:0];
    wire [3:0]  wstrb4      = wr_lane_sel ? wr_strb8[7:4]    : wr_strb8[3:0];

    // -------------------------------------------------------------------------
    // AW size conversion
    // -------------------------------------------------------------------------
    // VeeR MMIO (side-effect): AWSIZE in {0,1,2} -> forward unchanged (fits in 32-bit)
    // VeeR cacheable:          AWSIZE = 3'b011 (8-byte) -> convert to 3'b010 (4-byte)
    wire [2:0] m_awsize_conv = (wr_size == 3'b011) ? 3'b010 : wr_size;

    // -------------------------------------------------------------------------
    // Write master outputs
    // -------------------------------------------------------------------------
    assign m_axi_awid    = {{(M_ID_WIDTH-LSU_BUS_TAG){1'b0}}, wr_id};
    assign m_axi_awaddr  = wr_addr;
    assign m_axi_awlen   = 8'h00;           // Single beat always
    assign m_axi_awsize  = m_awsize_conv;
    assign m_axi_awburst = wr_burst;
    assign m_axi_awlock  = wr_lock;
    assign m_axi_awcache = wr_cache;
    assign m_axi_awprot  = wr_prot;
    assign m_axi_awqos   = wr_qos;
    assign m_axi_awuser  = 1'b0;

    assign m_axi_wdata   = wdata32;
    assign m_axi_wstrb   = wstrb4;
    assign m_axi_wlast   = 1'b1;            // VeeR is always single-beat
    assign m_axi_wuser   = 1'b0;

    // -------------------------------------------------------------------------
    // Write B channel relay
    // -------------------------------------------------------------------------
    // Present downstream B to VeeR only when in WS_BRESP state.
    assign s_axi_bvalid  = (wr_state == WS_BRESP) && m_axi_bvalid;
    assign s_axi_bid     = m_axi_bid[LSU_BUS_TAG-1:0];  // Lower nibble (upper always 0)
    assign s_axi_bresp   = m_axi_bresp;
    assign m_axi_bready  = (wr_state == WS_BRESP) && s_axi_bready;

    // =========================================================================
    // READ PATH STATE MACHINE
    // =========================================================================
    //
    //  RS_IDLE : waiting for AR from VeeR
    //  RS_CMD  : AR latched and being forwarded downstream
    //  RS_DATA : AR sent; waiting for RDATA from downstream

    localparam [1:0] RS_IDLE = 2'd0;
    localparam [1:0] RS_CMD  = 2'd1;
    localparam [1:0] RS_DATA = 2'd2;

    reg [1:0] rd_state, rd_state_next;

    // AR latch
    reg [LSU_BUS_TAG-1:0] rd_id;
    reg [31:0]            rd_addr;
    reg [2:0]             rd_size;
    reg [1:0]             rd_burst;
    reg                   rd_lock;
    reg [3:0]             rd_cache;
    reg [2:0]             rd_prot;
    reg [3:0]             rd_qos;

    // -------------------------------------------------------------------------
    // AR acceptance
    // -------------------------------------------------------------------------
    assign s_axi_arready = (rd_state == RS_IDLE);
    wire ar_take = s_axi_arvalid && s_axi_arready;

    // -------------------------------------------------------------------------
    // AR latch register
    // -------------------------------------------------------------------------
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            rd_id    <= {LSU_BUS_TAG{1'b0}};
            rd_addr  <= 32'b0;
            rd_size  <= 3'b0;
            rd_burst <= 2'b0;
            rd_lock  <= 1'b0;
            rd_cache <= 4'b0;
            rd_prot  <= 3'b0;
            rd_qos   <= 4'b0;
        end else begin
            if (ar_take) begin
                rd_id    <= s_axi_arid;
                rd_addr  <= s_axi_araddr;
                rd_size  <= s_axi_arsize;
                rd_burst <= s_axi_arburst;
                rd_lock  <= s_axi_arlock;
                rd_cache <= s_axi_arcache;
                rd_prot  <= s_axi_arprot;
                rd_qos   <= s_axi_arqos;
            end
        end
    end

    // -------------------------------------------------------------------------
    // Read state machine (combinational)
    // -------------------------------------------------------------------------
    always @(*) begin
        rd_state_next = rd_state;
        case (rd_state)
            RS_IDLE: begin
                if (ar_take)
                    rd_state_next = RS_CMD;
            end
            RS_CMD: begin
                if (m_axi_arvalid && m_axi_arready)
                    rd_state_next = RS_DATA;
            end
            RS_DATA: begin
                if (m_axi_rvalid && m_axi_rready)
                    rd_state_next = RS_IDLE;
            end
            default: rd_state_next = RS_IDLE;
        endcase
    end

    // Read state register
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            rd_state <= RS_IDLE;
        else
            rd_state <= rd_state_next;
    end

    // -------------------------------------------------------------------------
    // AR size conversion (same rule as write)
    // -------------------------------------------------------------------------
    wire [2:0] m_arsize_conv = (rd_size == 3'b011) ? 3'b010 : rd_size;

    // -------------------------------------------------------------------------
    // Read master outputs
    // -------------------------------------------------------------------------
    assign m_axi_arvalid = (rd_state == RS_CMD);
    assign m_axi_arid    = {{(M_ID_WIDTH-LSU_BUS_TAG){1'b0}}, rd_id};
    assign m_axi_araddr  = rd_addr;
    assign m_axi_arlen   = 8'h00;           // Single beat always
    assign m_axi_arsize  = m_arsize_conv;
    assign m_axi_arburst = rd_burst;
    assign m_axi_arlock  = rd_lock;
    assign m_axi_arcache = rd_cache;
    assign m_axi_arprot  = rd_prot;
    assign m_axi_arqos   = rd_qos;
    assign m_axi_aruser  = 1'b0;

    // -------------------------------------------------------------------------
    // Read data reconstruction
    // -------------------------------------------------------------------------
    // VeeR selects the half it needs with: buf_addr[i][2] ? rdata[63:32] : rdata[31:0]
    // So we must place the 32-bit downstream RDATA into the matching half.
    //
    //   rd_addr[2] == 0  ->  rdata64 = {32'b0,       m_rdata}
    //   rd_addr[2] == 1  ->  rdata64 = {m_rdata,       32'b0}

    wire [63:0] rdata64_out = rd_addr[2] ? {m_axi_rdata, 32'b0}
                                         : {32'b0, m_axi_rdata};

    // -------------------------------------------------------------------------
    // R channel relay to VeeR
    // -------------------------------------------------------------------------
    assign s_axi_rvalid  = (rd_state == RS_DATA) && m_axi_rvalid;
    assign s_axi_rid     = rd_id;           // Use our latched ID
    assign s_axi_rdata   = rdata64_out;
    assign s_axi_rresp   = m_axi_rresp;
    assign s_axi_rlast   = 1'b1;            // Always single-beat
    assign m_axi_rready  = (rd_state == RS_DATA) && s_axi_rready;

endmodule

`default_nettype wire
